name: CI - Build, Scan, and Push Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # The GitHub Container Registry
  REGISTRY: ghcr.io
  # The image name will be <owner>/<repo_name>
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write # Required to push to GHCR

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest

      - name: Build and push (pre-scan)
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pre-scan
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pre-scan'
          format: 'table'
          exit-code: '1' # Fail the build if issues are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' # Fail on HIGH or CRITICAL

      - name: Build and push (final)
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          # Push with the 'latest' and 'git-sha' tags
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
